spring:
  application:
    name: yld-supply-chain-v2
#  datasource:
#    dynamic:
#      primary: supply
#      datasource:
#        supply:
#          url: jdbc:mysql://192.168.50.3:22010/yld_supply_chain?useUnicode=true&characterEncoding=utf8&useSSL=false
#          username: scm
#          password: dkJ0VNcjLfZOn6ZPqM80505tIyougoNMUdwn400eOXJ2PYqhnZbzuKfFpNkJHZYNCdgjc3vGSocDNlfZ2E69qQ==
#          driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true
  aop:
    auto: true


#mybatisPlus
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: cn.com.yyxx.yld.supply.entity
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号隔离
  typeAliasesPackage: cn.com.yyxx.yld.supply.entity
  global-config:
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: NOT_EMPTY
      table-underline: true
    #自定义填充策略接口实现
    #meta-object-handler: cn.com.yyxx.yld.config.SysMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 600000
        loggerLevel: basic
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          semaphore:
            maxConcurrentRequests: 10000
          thread:
            timeoutInMilliseconds: 1080000
  threadpool:
    default:
      coreSize: 10
      maximumSize: 500
      allowMaximumSizeToDivergeFromCoreSize: true

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 600000


socket:
    http:
    socketip:
    port:

logging.level.com.alibaba.nacos.client.naming: error
